apiVersion: v1
kind: Service  # optimizer.default.svc.cluster.local
metadata:
  name: optimizer
  namespace: default
  labels:
    run: optimizer
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    run: optimizer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimizer
spec:
  selector:
    matchLabels:
      run: optimizer
  replicas: 1
  template:
    metadata:
      labels:
        run: optimizer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: DoesNotExist
      volumes:
      - name: gcs-secret
        secret:
          secretName: gcs-admin-secret
          items:
          - key: sa_json
            path: sa_credentials.json
      containers:
      - name: optimizer
        image: gcr.io/dotaservice-225201/dotaclient:latest
        command: ["python3.7", "dotaoptimizer.py"]
        volumeMounts:
        - name: gcs-secret
          mountPath: /etc/gcp
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/gcp/sa_credentials.json
        ports:
        - name: grpc
          containerPort: 50051
        resources:
          requests:
            cpu: 400m  # ~80m per dotaservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotaservice-deployment
  labels:
    app: dotaservice
spec:
  replicas: 12
  selector:
    matchLabels:
      app: dotaservice
  template:
    metadata:
      labels:
        app: dotaservice
    spec:
      nodeSelector:
        cloud.google.com/gke-preemptible: "true"
      containers:
      - name: client
        image: gcr.io/dotaservice-225201/dotaclient:latest
        command:
        - python3.7
        - client.py
        - --ip
        - optimizer.default.svc.cluster.local
        resources:
          requests:
            cpu: 100m
      - name: dotaservice
        image: gcr.io/dotaservice-225201/dotaservice:0.3.0f
        ports:
        - containerPort: 13337
        resources:
          requests:
            cpu: 500m

# TODO(tzaman): add rabbitmq for experience broker
# docker run 15672:15672 -p 5672:5672 rabbitmq:3.7.8-management-alpine