apiVersion: v1
kind: Service  # rmq.default.svc.cluster.local
metadata:
  name: rmq
  namespace: default
  labels:
    run: rmq
spec:
  type: ClusterIP
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
  selector:
    run: rmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq
spec:
  selector:
    matchLabels:
      run: rmq
  replicas: 1
  template:
    metadata:
      labels:
        run: rmq
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: DoesNotExist
      containers:
      - name: rmq
        image: gcr.io/dotaservice-225201/rmq:3.7-plugins-a
        ports:
          - name: http
            protocol: TCP
            containerPort: 15672
          - name: amqp
            protocol: TCP
            containerPort: 5672
        resources:
          requests:
            cpu: 200m
            memory: 1024Mi
---
apiVersion: "kubeflow.org/v1beta1"
kind: "PyTorchJob"
metadata:
  name: "optimizer"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template: 
        spec:
          volumes:
          - name: gcs-secret
            secret:
              secretName: gcs-admin-secret
              items:
              - key: sa_json
                path: sa_credentials.json
          containers:
            - name: pytorch
              image: gcr.io/dotaservice-225201/dotaclient:latest
              command:
              - python3.7
              - optimizer.py
              - --ip
              - rmq.default.svc.cluster.local
              - --batch-size
              - "8"
              resources:
                requests:
                  cpu: 400m
              volumeMounts:
              - name: gcs-secret
                mountPath: /etc/gcp
                readOnly: true
    Worker:
      replicas: 3
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: gcr.io/dotaservice-225201/dotaclient:latest
              command:
              - python3.7
              - optimizer.py
              - --ip
              - rmq.default.svc.cluster.local
              - --batch-size
              - "8"
              resources:
                requests:
                  cpu: 400m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotaservice-deployment
  labels:
    app: dotaservice
spec:
  replicas: 32
  selector:
    matchLabels:
      app: dotaservice
  template:
    metadata:
      labels:
        app: dotaservice
    spec:
      nodeSelector:
        cloud.google.com/gke-preemptible: "true"
      containers:
      - name: agent
        image: gcr.io/dotaservice-225201/dotaclient:latest
        command:
        - python3.7
        - agent.py
        - --ip
        - rmq.default.svc.cluster.local
        resources:
          requests:
            cpu: 100m
      - name: dotaservice
        image: gcr.io/dotaservice-225201/dotaservice:0.3.0f
        ports:
        - containerPort: 13337
        resources:
          requests:
            cpu: 500m
            memory: 1408Mi
