apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotaservice-deployment
  labels:
    app: dotaservice
spec:
  replicas: 7
  selector:
    matchLabels:
      app: dotaservice
  template:
    metadata:
      labels:
        app: dotaservice
    spec:
      volumes:
      - name: ramdisk
        emptyDir:
          medium: "Memory"
      nodeSelector:
        cloud.google.com/gke-preemptible: "true"
      containers:
      - name: agent
        image: gcr.io/dotaservice-225201/dotaclient:latest
        command: ["python3.7", "agent.py"]
        args: ["--ip", "rmq.default.svc.cluster.local", "--rollout-size", "99999", "--max-dota-time", "210"]
        resources:
          requests:
            cpu: 700m
      - name: dotaservice
        image: gcr.io/dotaservice-225201/dotaservice:0.3.3
        command: ["python3.7", "-m", "dotaservice"]
        args: ["--action-path", "/ramdisk"]
        volumeMounts:
        - mountPath: /ramdisk
          name: ramdisk
        ports:
        - containerPort: 13337
        resources:
          requests:
            cpu: 800m
            memory: 1536Mi
