apiVersion: "kubeflow.org/v1beta1"
kind: "PyTorchJob"
metadata:
  name: "optimizer"
spec:
  terminationGracePeriodSeconds: 30
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template: 
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: DoesNotExist
          volumes:
          - name: gcs-secret
            secret:
              secretName: gcs-admin-secret
              items:
              - key: sa_json
                path: sa_credentials.json
          containers:
          - name: pytorch
            image: gcr.io/dotaservice-225201/dotaclient:latest
            command: ["python3.7", "optimizer.py"]
            args: ["--ip", "rmq.default.svc.cluster.local", "--batch-size", "8", "--learning-rate", "1e-4"]
            volumeMounts:
            - name: gcs-secret
              mountPath: /etc/gcp
              readOnly: true
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/sa_credentials.json
            resources:
              requests:
                cpu: 600m
    # Worker:
    #   replicas: 0
    #   restartPolicy: OnFailure
    #   template:
    #     spec:
    #       affinity:
    #         nodeAffinity:
    #           requiredDuringSchedulingIgnoredDuringExecution:
    #             nodeSelectorTerms:
    #             - matchExpressions:
    #               - key: cloud.google.com/gke-preemptible
    #                 operator: DoesNotExist
    #       containers:
    #       - name: pytorch
    #         image: gcr.io/dotaservice-225201/dotaclient:latest
    #         command: ["python3.7", "optimizer.py"]
    #         args: ["--ip", "rmq.default.svc.cluster.local", "--batch-size", "8", "--learning-rate", "1e-4"]
    #         resources:
    #           requests:
    #             cpu: 600m
